plugins {
    alias(libs.plugins.java)
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

group = 'ru.skripov'
version = '1.0.0'
description = 'resume_back'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    configureEach {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springModulithVersion', libs.versions.spring.modulith.get())
}

dependencies {
    implementation libs.bundles.spring.web

    implementation 'org.springframework.boot:spring-boot-h2console'
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-restclient'
    implementation 'org.springframework.boot:spring-boot-configuration-processor'
    developmentOnly 'org.springframework.boot:spring-boot-docker-compose'

    //database
    implementation libs.bundles.spring.data
    implementation libs.bundles.database

    //lombok
    compileOnly libs.bundles.lombok.set
    annotationProcessor libs.bundles.lombok.set

    //Логирование
    implementation libs.bundles.logging

    //kafka
    implementation 'org.springframework.kafka:spring-kafka'

    //modules
    implementation project(':security')

    //tests
    testImplementation libs.bundles.testing
    testImplementation libs.spring.modulith.starter.test

    testImplementation 'org.springframework.boot:spring-boot-starter-restclient-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.modulith:spring-modulith-bom:${springModulithVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
