plugins {
    alias(libs.plugins.java)
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

group = 'ru.skripov'
version = '1.0.0'
description = 'resume_back'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    configureEach {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springModulithVersion', libs.versions.spring.modulith.get())
}

dependencies {
    implementation libs.bundles.spring.web

    //dev utils
    developmentOnly libs.spring.boot.configuration.processor
    annotationProcessor libs.spring.boot.configuration.processor

    //database
    implementation libs.bundles.spring.data
    implementation libs.bundles.database

    //Для работы MapStruct + Lombok
    implementation libs.bundles.mapstruct
    compileOnly libs.bundles.lombok.mapstruct.compile
    annotationProcessor libs.bundles.lombok.mapstruct.processor

    //Логирование
    implementation libs.bundles.logging

    //kafka
    implementation libs.spring.kafka

    //docker
    developmentOnly libs.bundles.docker

    //modules
    implementation project(':security')

    //tests
    testImplementation libs.bundles.testing
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.modulith:spring-modulith-bom:${springModulithVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
