server:
  port: 8090

spring:
  application:
    name: resume_back
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/my_resume?useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true #Включаем sql отладку
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #liquibase settings
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true

  docker:
    compose:
      #Выключить запуск в докере
      enabled: false

  threads:
    virtual:
      enabled: true

jwt:
  # Секрет в base64 (минимум 32 символа)
  secret: ${JWT_SECRET}
  expiration: 86400

  # Время жизни в секундах
  access-token-expiration: 900        # 15 минут
  refresh-token-expiration: 604800    # 7 дней

  # Дополнительные настройки
  issuer: resume-back-app
  audience: resume-back-users

  # Настройки безопасности
  header: Authorization
  prefix: "Bearer "
  cookie-name: jwt_token

#sql debugging
logging:
  config: classpath:log4j2-spring.xml
  charset:
    console: UTF-8
    file: UTF-8
  level:
    liquibase: INFO
    # Уровень логирования
    root: INFO
    ru.skripov: INFO
    # Вывод исключений
    org:
      springframework: WARN
      hibernate: INFO
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE