[versions]
# Spring
spring-boot = "4.0.0"
spring-modulith = "2.0.0"
spring-security-test = "7.0.2"

# Security
jjwt = "0.13.0"

# Database
postgresql = "42.7.8"
h2 = "2.4.240"
liquibase = "5.0.1"

# Utilities
lombok = "1.18.42"
mapstruct = "1.6.3"
lombok-mapstruct-binding = "0.2.0"

# Logging
log4j = "2.25.3"

# Kafka
spring-kafka = "3.2.5"

# Swagger
springdoc = "2.6.0"

# Testing
junit = "4.13.2"
junit-platform = "6.0.1"

[libraries]
# Spring Boot Starters
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc", version.ref = "spring-boot" }
spring-boot-starter-restclient = { module = "org.springframework.boot:spring-boot-starter-restclient", version.ref = "spring-boot" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc", version.ref = "spring-boot" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot" }
spring-boot-docker-compose = { module = "org.springframework.boot:spring-boot-docker-compose", version.ref = "spring-boot" }
spring-boot-h2console = { module = "org.springframework.boot:spring-boot-h2console", version.ref = "spring-boot" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }

# Spring Modulith
spring-modulith-starter-test = { module = "org.springframework.modulith:spring-modulith-starter-test", version.ref = "spring-modulith" }

# JWT
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

# Database
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
liquibase-core = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }

# Utilities
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
lombok-mapstruct-binding = { module = "org.projectlombok:lombok-mapstruct-binding", version.ref = "lombok-mapstruct-binding" }

# Logging
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }

# Kafka
spring-kafka = { module = "org.springframework.kafka:spring-kafka", version.ref = "spring-kafka" }

# Swagger
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

# Testing
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
spring-security-test = { module = "org.springframework.security:spring-security-test", version.ref = "spring-security-test" }

[bundles]
spring-web = [
    "spring-boot-starter-web",
    "spring-boot-starter-security",
    "spring-boot-starter-webmvc"
]

spring-data = [
    "spring-boot-starter-data-jpa",
    "spring-boot-starter-jdbc"
]

jwt = [
    "jjwt-api",
    "jjwt-impl",
    "jjwt-jackson"
]

database = [
    "postgresql",
    "liquibase-core"
]

logging = [
    "log4j-core",
    "log4j-slf4j2-impl"
]

lombok-set = [
    "lombok",
    "mapstruct",
    "mapstruct-processor",
    "lombok-mapstruct-binding"
]

testing = [
    "spring-boot-starter-test",
    "spring-security-test",
    "h2",
    "junit",
    "junit-platform-launcher"
]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
java = { id = "java", version = "" }