plugins {
    id 'java'
}

group = 'ru.skripov'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    configureEach {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.bundles.spring.web

    //Рефлексия
    implementation libs.reflections

    //Логирование
    implementation libs.bundles.logging

    //Для работы MapStruct + Lombok
    implementation libs.bundles.mapstruct
    compileOnly libs.bundles.lombok.mapstruct.compile
    annotationProcessor libs.bundles.lombok.mapstruct.processor

    //swagger
    implementation libs.bundles.swagger

    // HTTP клиент
    implementation libs.okhttp
}