plugins {
    alias(libs.plugins.java)
}

group = 'ru.skripov'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    configureEach {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.bundles.spring.web

    //database
    implementation libs.bundles.spring.data
    implementation libs.bundles.database

    //JWT
    implementation libs.bundles.jwt

    //Логирование
    implementation libs.bundles.logging

    //swagger
    implementation libs.springdoc.openapi.starter.webmvc.ui

    //Для работы MapStruct + Lombok
    implementation libs.bundles.mapstruct
    compileOnly libs.bundles.lombok.mapstruct.compile
    annotationProcessor libs.bundles.lombok.mapstruct.processor

    //modules
    implementation project(':base_module')

    testImplementation libs.bundles.testing
}