plugins {
    alias(libs.plugins.java)
}

group = 'ru.skripov'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    configureEach {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.bundles.spring.web
    implementation libs.bundles.spring.data

    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.entur.jwt-rs:jwt-client-spring-core:5.2.2'

    //JWT
    implementation libs.bundles.jwt

    //Логирование
    implementation libs.bundles.logging

    //swagger
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui'

    //mapper
    implementation "org.mapstruct:mapstruct"
    annotationProcessor "org.mapstruct:mapstruct-processor"
    //Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    //Для работы MapStruct + Lombok
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding'

    //modules
    implementation project(':base_module')

    testImplementation 'org.springframework.security:spring-security-test'
}